### ISSUE TITLE
Question: Is there any plan to support terraform version 0.15.x for this tool?

### ISSUE THREAD

**Issue by scalar-kato** [scalar-labs/scalar-terraform#317]
I got an error when I used this tool with v0.15.4 terraform. Are there any plans to support v0.15.x terraform in the future?
If you do, please let me know when it will be available.

**Comment by tei-k** [comment]
Since `1.0` is already in GA, there are no plans to support the `0.15` at this time!

https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability

We need to discuss with @feeblefakie san about when to support `1.0` version.

Please let us know if you have any requests for versions or support dates for your project.
